sudo: required
language: generic
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
services: 
    - docker

before_install:
    - docker build -t rdthomashoutekier/ud-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rdthomashoutekier/ud-docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "ud-docker-react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-jfjfjf"
    bucket_path: "ud-docker-react"
    on:
        branch: master