sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t rdthomashoutekier/ud-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rdthomashoutekier/ud-docker-react npm run test -- --coverage